name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade poetry
          poetry install --with dev
      - name: Install cg3
        run: sudo apt install -y cg3
      - name: Test with pytest
        run: |
          poetry run pytest test